# Generated by Django 5.1.4 on 2024-12-13 00:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.basemodel')),
            ],
            bases=('journal.basemodel',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.widget')),
                ('name', models.CharField(max_length=64)),
                ('datetime', models.DateTimeField()),
            ],
            bases=('journal.widget',),
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.widget')),
                ('title', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('status', models.IntegerField(default=0)),
            ],
            bases=('journal.widget',),
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.widget')),
                ('prompt_text', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('response_text', models.TextField()),
            ],
            bases=('journal.widget',),
        ),
    ]
