# Generated by Django 5.1.4 on 2025-01-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='event_datetime',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='date',
            new_name='habit_date',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='date',
            new_name='prompt_date',
        ),
    ]
